// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX6IfoAv2ttWn2kN-wjh3_zPXeELwiHwI',
    appId: '1:927539259838:web:b80cb1a2a36c5abe65f1ef',
    messagingSenderId: '927539259838',
    projectId: 'qubit-8e3ba',
    authDomain: 'qubit-8e3ba.firebaseapp.com',
    storageBucket: 'qubit-8e3ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEAnLReACaVAGmXm7UpWfon1KKoXXJeBg',
    appId: '1:927539259838:android:47d63275a9610cb265f1ef',
    messagingSenderId: '927539259838',
    projectId: 'qubit-8e3ba',
    storageBucket: 'qubit-8e3ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB0Hy8J2EucIazlo0q1Mk2foqBaQP4h-I',
    appId: '1:927539259838:ios:2b831c509f002cad65f1ef',
    messagingSenderId: '927539259838',
    projectId: 'qubit-8e3ba',
    storageBucket: 'qubit-8e3ba.firebasestorage.app',
    iosBundleId: 'com.example.qubit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB0Hy8J2EucIazlo0q1Mk2foqBaQP4h-I',
    appId: '1:927539259838:ios:2b831c509f002cad65f1ef',
    messagingSenderId: '927539259838',
    projectId: 'qubit-8e3ba',
    storageBucket: 'qubit-8e3ba.firebasestorage.app',
    iosBundleId: 'com.example.qubit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX6IfoAv2ttWn2kN-wjh3_zPXeELwiHwI',
    appId: '1:927539259838:web:fc8fcfefd124754565f1ef',
    messagingSenderId: '927539259838',
    projectId: 'qubit-8e3ba',
    authDomain: 'qubit-8e3ba.firebaseapp.com',
    storageBucket: 'qubit-8e3ba.firebasestorage.app',
  );
}
